import {Injectable} from '@angular/core';
declare var _:any;

@Injectable()
export class ZipResults {
    getEvents() {
        return ZIPCODES;
    }

    getZip(id) {
        return _.get(ZIPCODES, id)
    }
}
const ZIPCODES = {
    "00501": {
        "city": "HOLTSVILLE",
        "county": "SUFFOLK",
        "state": "NY",
        "windcode": "W0",
        "zip": "00501",
        "citytax": 0,
        "countytax": 0,
        "statetax": 8.625,
        "Stores": [
            {
                "storenumber": "1258",
                "storename": "PATCHOGUE WEST ",
                "address1": "10 GATEWAY BLVD ",
                "address2": " ",
                "city": "PATCHOGUE ",
                "state": "NY",
                "zip": "11772",
                "storephonenumber": "6312864665",
                "zipdistance": "3.754135",
                "marketid": "20",
                "comminstall": "False",
                "natmarketid": "9000",
                "gdo": "C",
                "storegdo": "C",
                "isResidential": true,
                "isCommercial": true,
                "isService": false,
                "storetax": "8.62500",
                "active": "True",
                "productlayout": "False",
                "DoubleDoorHeight": "7",
                "DoubleDoorWidth": "16",
                "SingleDoorHeight": "7",
                "SingleDoorWidth": "8",
                "URLVersion": "version2"
            },
            {
                "storenumber": "1209",
                "storename": "SELDEN ",
                "address1": "401 INDEPENDENCE PLAZA ",
                "address2": " ",
                "city": "SELDEN ",
                "state": "NY",
                "zip": "11784",
                "storephonenumber": "6317329200",
                "zipdistance": "3.848556",
                "marketid": "20",
                "comminstall": "False",
                "natmarketid": "9000",
                "gdo": "C",
                "storegdo": "C",
                "isResidential": true,
                "isCommercial": true,
                "isService": false,
                "storetax": "8.62500",
                "active": "True",
                "productlayout": "False",
                "DoubleDoorHeight": "7",
                "DoubleDoorWidth": "16",
                "SingleDoorHeight": "7",
                "SingleDoorWidth": "8",
                "URLVersion": "version2"
            },
            {
                "storenumber": "1265",
                "storename": "SOUTH SETAUKET ",
                "address1": "255 POND PATH ",
                "address2": " ",
                "city": "SOUTH SETAUKET ",
                "state": "NY",
                "zip": "11720",
                "storephonenumber": "6315807849",
                "zipdistance": "4.000458",
                "marketid": "20",
                "comminstall": "False",
                "natmarketid": "9000",
                "gdo": "C",
                "storegdo": "C",
                "isResidential": true,
                "isCommercial": true,
                "isService": false,
                "storetax": "8.62500",
                "active": "True",
                "productlayout": "False",
                "DoubleDoorHeight": "7",
                "DoubleDoorWidth": "16",
                "SingleDoorHeight": "7",
                "SingleDoorWidth": "8",
                "URLVersion": "version2"
            }
        ]
    },
    "00544": {
        "city": "HOLTSVILLE",
        "county": "SUFFOLK",
        "state": "NY",
        "windcode": "W0",
        "zip": "00544",
        "citytax": 0,
        "countytax": 0,
        "statetax": 8.625,
        "Stores": [
            {
                "storenumber": "1258",
                "storename": "PATCHOGUE WEST ",
                "address1": "10 GATEWAY BLVD ",
                "address2": " ",
                "city": "PATCHOGUE ",
                "state": "NY",
                "zip": "11772",
                "storephonenumber": "6312864665",
                "zipdistance": "3.754135",
                "marketid": "20",
                "comminstall": "False",
                "natmarketid": "9000",
                "gdo": "C",
                "storegdo": "C",
                "isResidential": true,
                "isCommercial": true,
                "isService": false,
                "storetax": "8.62500",
                "active": "True",
                "productlayout": "False",
                "DoubleDoorHeight": "7",
                "DoubleDoorWidth": "16",
                "SingleDoorHeight": "7",
                "SingleDoorWidth": "8",
                "URLVersion": "version2"
            },
            {
                "storenumber": "1209",
                "storename": "SELDEN ",
                "address1": "401 INDEPENDENCE PLAZA ",
                "address2": " ",
                "city": "SELDEN ",
                "state": "NY",
                "zip": "11784",
                "storephonenumber": "6317329200",
                "zipdistance": "3.848556",
                "marketid": "20",
                "comminstall": "False",
                "natmarketid": "9000",
                "gdo": "C",
                "storegdo": "C",
                "isResidential": true,
                "isCommercial": true,
                "isService": false,
                "storetax": "8.62500",
                "active": "True",
                "productlayout": "False",
                "DoubleDoorHeight": "7",
                "DoubleDoorWidth": "16",
                "SingleDoorHeight": "7",
                "SingleDoorWidth": "8",
                "URLVersion": "version2"
            },
            {
                "storenumber": "1265",
                "storename": "SOUTH SETAUKET ",
                "address1": "255 POND PATH ",
                "address2": " ",
                "city": "SOUTH SETAUKET ",
                "state": "NY",
                "zip": "11720",
                "storephonenumber": "6315807849",
                "zipdistance": "4.000458",
                "marketid": "20",
                "comminstall": "False",
                "natmarketid": "9000",
                "gdo": "C",
                "storegdo": "C",
                "isResidential": true,
                "isCommercial": true,
                "isService": false,
                "storetax": "8.62500",
                "active": "True",
                "productlayout": "False",
                "DoubleDoorHeight": "7",
                "DoubleDoorWidth": "16",
                "SingleDoorHeight": "7",
                "SingleDoorWidth": "8",
                "URLVersion": "version2"
            }
        ]
    },
    "00601": {
        "city": "ADJUNTAS",
        "county": "ADJUNTAS",
        "state": "PR",
        "windcode": "W0",
        "zip": "00601",
        "citytax": 0,
        "countytax": 0,
        "statetax": 7.5,
        "Stores": []
    },
    "00602": {
        "city": "AGUADA",
        "county": "AGUADA",
        "state": "PR",
        "windcode": "W0",
        "zip": "00602",
        "citytax": 0,
        "countytax": 0,
        "statetax": 7.5,
        "Stores": []
    },
    "00603": {
        "city": "RAMEY",
        "county": "AGUADILLA",
        "state": "PR",
        "windcode": "W0",
        "zip": "00603",
        "citytax": 0,
        "countytax": 0,
        "statetax": 7.5,
        "Stores": []
    },
    "00604": {
        "city": "RAMEY",
        "county": "AGUADILLA",
        "state": "PR",
        "windcode": "W0",
        "zip": "00604",
        "citytax": 0,
        "countytax": 0,
        "statetax": 7.5,
        "Stores": []
    }
}