import {Injectable} from '@angular/core';
declare var _:any;

@Injectable()
export class ZipResults {
    getEvents() {
        return ZIPCODES;
    }
    getZip(id){
       return  _.get(ZIPCODES, id)
    }
}
const ZIPCODES = {
    "60123": [
        {
            DoubleDoorHeight: "7",
            DoubleDoorWidth: "16",
            SingleDoorHeight: "7",
            SingleDoorWidth: "8",
            URLVersion: "version2",
            active: "true",
            address1: "955 N RANDALL RD ",
            address2: " ",
            city: "ELGIN ",
            comminstall: "False",
            county: null,
            gdo: "CG",
            isCommercial: true,
            isResidential: true,
            isService: false,
            marketid: "75",
            natmarketid: "6000",
            productlayout: "True",
            state: "IL",
            storegdo: "CG",
            storename: "ELGIN ",
            storenumber: "1934",
            storephonenumber: "8476229441",
            storetax: "7.75000",
            windcode: null,
            zip: "60123",
            zipdistance: "0"
        },
        {
            DoubleDoorHeight: "7",
            DoubleDoorWidth: "16",
            SingleDoorHeight: "7",
            SingleDoorWidth: "8",
            URLVersion: "version2",
            active: "true",
            address1: "440 RANDALL ROAD ",
            address2: " ",
            city: "SOUTH ELGIN ",
            comminstall: "False",
            county: null,
            gdo: "CG",
            isCommercial: true,
            isResidential: true,
            isService: false,
            marketid: "75",
            natmarketid: "6000",
            productlayout: "True",
            state: "IL",
            storegdo: "CG",
            storename: "SOUTH ELGIN ",
            storenumber: "6923",
            storephonenumber: "8472148718",
            storetax: "7.50000",
            windcode: null,
            zip: "60177",
            zipdistance: "3.556287"
        },
        {
            DoubleDoorHeight: "7",
            DoubleDoorWidth: "16",
            SingleDoorHeight: "7",
            SingleDoorWidth: "8",
            URLVersion: "version2",
            active: "true",
            address1: "251 SPRING HILL ROAD ",
            address2: " ",
            city: "CARPENTERSVILLE ",
            comminstall: "False",
            county: null,
            gdo: "CG",
            isCommercial: true,
            isResidential: true,
            isService: true,
            marketid: "75",
            natmarketid: "6000",
            productlayout: "True",
            state: "IL",
            storegdo: "CG",
            storename: "W DUNDEE/CARPENTERSVILLE",
            storenumber: "1948",
            storephonenumber: "8477830766",
            storetax: "8.50000",
            windcode: null,
            zip: "60110",
            zipdistance: "5.697083"
        }
    ],
    "61523": [
        {
            DoubleDoorHeight: "7",
            DoubleDoorWidth: "16",
            SingleDoorHeight: "7",
            SingleDoorWidth: "9",
            URLVersion: "version2",
            active: "true",
            address1: "5026 W HOLIDAY DRIVE ",
            address2: " ",
            city: "PEORIA ",
            comminstall: "False",
            county: null,
            gdo: "CG",
            isCommercial: true,
            isResidential: true,
            isService: false,
            marketid: "304",
            natmarketid: "6000",
            productlayout: "False",
            state: "IL",
            storegdo: "",
            storename: "PEORIA,IL ",
            storenumber: "1978",
            storephonenumber: "3096933819",
            storetax: "8.25000",
            windcode: null,
            zip: "61615",
            zipdistance: "12.58571"
        },
        {
            DoubleDoorHeight: "7",
            DoubleDoorWidth: "16",
            SingleDoorHeight: "7",
            SingleDoorWidth: "9",
            URLVersion: "version2",
            active: "true",
            address1: "4242 VENTURE DRIVE ",
            address2: " ",
            city: "PERU ",
            comminstall: "False",
            county: null,
            gdo: "CG",
            isCommercial: true,
            isResidential: true,
            isService: false,
            marketid: "304",
            natmarketid: "6000",
            productlayout: "False",
            state: "IL",
            storegdo: "",
            storename: "PERU ",
            storenumber: "1977",
            storephonenumber: "8152242968",
            storetax: "7.00000",
            windcode: null,
            zip: "61354",
            zipdistance: "35.66362"
        },
        {
            DoubleDoorHeight: "7",
            DoubleDoorWidth: "16",
            SingleDoorHeight: "7",
            SingleDoorWidth: "9",
            URLVersion: "version2",
            active: "true",
            address1: "795 VETERANS PARKWAY ",
            address2: " ",
            city: "NORMAL ",
            comminstall: "False",
            county: null,
            gdo: "CG",
            isCommercial: true,
            isResidential: true,
            isService: false,
            marketid: "304",
            natmarketid: "6000",
            productlayout: "False",
            state: "IL",
            storegdo: "",
            storename: "NORMAL ",
            storenumber: "6987",
            storephonenumber: "3094524031",
            storetax: "7.75000",
            windcode: null,
            zip: "61761",
            zipdistance: "38.5806"
        }
    ]
};